changelog-file=changelogs/DWH.changelog.xml
url=jdbc:postgresql://localhost:5433/postgres
username=postgres
password=secret

liquibase.licenseKey=hashicorp,secret/data/liquibase/license,pro_key
vault.addr=http://localhost:8200
vault.token=vault-plaintext-root-token