##########           LIQUIBASE FLOWFILE - ROLLBACK BY COUNT    ##########
##########  learn more http://docs.liquibase.com/flow          ##########

## USAGE:
## export ROLLBACK_COUNT=3
## liquibase flow --flow-file=liquibase.flowfile.rollback-by-count.yaml
##
## EXAMPLES:
## export ROLLBACK_COUNT=1   # Rollback last changeset
## export ROLLBACK_COUNT=5   # Rollback last 5 changesets

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.
stages:

  ## Rollback by count stage
  Default:
        
    actions:
      #
      # Rollback last N changesets
      #
      - type: liquibase
        command: rollback-count
        cmdArgs: {count: "${ROLLBACK_COUNT}"}

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history