##########           LIQUIBASE FLOWFILE - ROLLBACK BY TAG      ##########
##########  learn more http://docs.liquibase.com/flow          ##########

## USAGE:
## export TAG_NAME=v1.0.0
## liquibase flow --flow-file=liquibase.flowfile.rollback-by-tag.yaml
##
## EXAMPLES:
## export TAG_NAME=v1.0.0              # Rollback to v1.0.0 tag
## export TAG_NAME=pre-deployment      # Rollback to pre-deployment tag
## export TAG_NAME=before-feature-x    # Rollback to before-feature-x tag

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.
stages:

  ## Rollback to tag stage
  Default:
        
    actions:
      #
      # Rollback to specific tag
      #
      - type: liquibase
        command: rollback
        cmdArgs: {tag: "${TAG_NAME}"}

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history