###
### This sample pipeline is intended as a starting point for integration between Liquibase Secure and Azure DevOps pipelines
### Review and update prior to use
###
### Liquibase version: 4.30.0+
###
### Liquibase sales: https://www.liquibase.com/contact
### Liquibase support: https://support.liquibase.com
### 

###
### Prior to running the following files must exist in repository:
###
### 1. liquibase.flowfile.yaml
###    Liquibase flow file
###    https://docs.liquibase.com/commands/flow/flow.html
###
### 2. liquibase.checks-settings.conf
###    Liquibase policy checks configuration file
###    https://docs.liquibase.com/liquibase-pro/policy-checks/home.html
###
### 3. changelog.main.xml
###    Liquibase changelog file
###    https://docs.liquibase.com/concepts/changelogs/home.html
###

###
### Azure pipelines documentation: https://aka.ms/yaml
###

###
### Pipelines can be triggered manually or via events
###
trigger: none

###
### Set pipeline variables
###
parameters:
  - name: labels
    displayName: Label filters
    type: string
    default: NONE
  - name: schemas
    displayName: Schemas
    type: string
    default: HumanResources,Person,Production,Purchasing,Sales
  - name: policyChecks
    displayName: Policy checks T/F
    type: string
    default: T
    values:
      - T
      - F
  - name: driftDetection
    displayName: Drift detection T/F
    type: string
    default: T
    values:
      - T
      - F
  - name: testRollbacks
    displayName: Test rollback scripts T/F
    type: string
    default: T
    values:
      - T
      - F

###
### Set Liquibase environment variables
###
variables:
###
### Prompts
###
### ADO doesn't currently allow optional parameters, so set if not equal to "NONE"
###
  ${{ if ne(parameters.labels, 'NONE')}}:
    LB_LABELS: ${{ parameters.labels }}
  LB_SCHEMAS: ${{ parameters.schemas }}
  LB_TEST_CHECKS: ${{ parameters.policyChecks }}
  LB_TEST_DRIFT: ${{ parameters.driftDetection }}
  LB_TEST_ROLLBACKS: ${{ parameters.testRollbacks }}
###
### Liquibase specific
###
  LB_BASE_DIR: /liquibase/changelog
  LB_ENVIRONMENT: DEV
  LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog.main.xml
  LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT: issues
  LIQUIBASE_DBCLHISTORY_ENABLED: true
  LIQUIBASE_LOG_FILE: /liquibase/changelog/liquibase.dev.log.json
  LIQUIBASE_LOG_FORMAT: json_pretty
  LIQUIBASE_LOG_LEVEL: warning
  LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG: false
  LIQUIBASE_SEARCH_PATH: /liquibase/changelog
  LIQUIBASE_SHOW_BANNER: false

###
### Utilizes a public Linux agent with git and docker available
### https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser
###
stages:
- stage: Liquibase
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Liquibase
    workspace:
      clean: all
    steps:
###
### Checkout repository
###
    - checkout: self
###
### Retrieve secrets
###
    - task: AzureKeyVault@2
      inputs:
        ### Create service connection from pipeline, (azureSubscriptiopn is the name chosen when creating
        ### the connection the connection name properties, requires Key Vault Secrets User role
        azureSubscription: 'sademo-sqlserver'
        KeyVaultName: 'sademo-sqlserver'
        SecretsFilter: '*'
        RunAsPreJob: false
      displayName: 'Retrieving secrets'
###
### Run the Liquibase flowfile
### Liquibase should be installed where your agents run or invoked via Docker
###
    - script: |
        docker run --env LIQUIBASE_SEARCH_PATH --env LIQUIBASE_SHOW_BANNER --env LIQUIBASE_DBCLHISTORY_ENABLED \
        --env LIQUIBASE_COMMAND_USERNAME --env LIQUIBASE_COMMAND_PASSWORD --env LIQUIBASE_COMMAND_URL \
        --env LIQUIBASE_LICENSE_KEY --env LIQUIBASE_COMMAND_CHANGELOG_FILE --env LIQUIBASE_COMMAND_CHECKS_RUN_CHECKS_OUTPUT \
        --env LIQUIBASE_LOG_FILE --env LIQUIBASE_LOG_FORMAT --env LIQUIBASE_LOG_LEVEL \
        --env LIQUIBASE_MIRROR_CONSOLE_MESSAGES_TO_LOG --env LB_BASE_DIR --env LB_ENVIRONMENT --env LB_LABELS --env LB_SCHEMAS \
        --env LB_TEST_DRIFT --env LB_TEST_CHECKS --env LB_TEST_ROLLBACKS --rm -v $(Build.SourcesDirectory):/liquibase/changelog \
        liquibase/liquibase-secure:latest flow --flow-file=liquibase.flowfile.yaml
###
### These values should be pulled from pipeline variables or vault
### https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-secret-variables?view=azure-devops&tabs=yaml%2Cbash
### Secrets should include LIQUIBASE_COMMAND_URL, LIQUIBASE_COMMAND_USERNAME, LIQUIBASE_COMMAND_PASSWORD, LIQUIBASE_LICENSE_KEY
###
      env:
        LIQUIBASE_COMMAND_URL: $(LIQUIBASE-DEV-URL)
        LIQUIBASE_COMMAND_USERNAME: $(LIQUIBASE-DEV-USER)
        LIQUIBASE_COMMAND_PASSWORD: $(LIQUIBASE-DEV-PASSWORD)
        LIQUIBASE_LICENSE_KEY: $(LIQUIBASE-KEY)
      displayName: 'Running Liquibase'
###
### Copy files to artifacts
###
    - task: CopyFiles@2
      inputs:
        contents: |
          *.html
          *.json
        targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copying files'
      condition: succeededOrFailed()
###
### Update artifacts
###
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: Artifacts-$(LB_ENVIRONMENT)
      displayName: 'Updating artifacts'
      condition: succeededOrFailed()
###
### Update repository
###
    - script: |
        git switch -c main
        git remote set-url origin https://ado-user:${LB_REPO_TOKEN}@dev.azure.com/molivas-pipelines/Azure_SQL_Server/_git/Azure_SQL_Server
        git config user.name ado-pipelines
        git config user.email ado-pipelines@microsoft.com
        git add .
        git commit -am "Update repository"
        git push -u origin main --force
      env: 
        LB_REPO_TOKEN: $(LIQUIBASE-REPO-TOKEN)
      displayName: 'Updating repository'
      condition: succeededOrFailed()
